apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
    spec:
      #assigned to master node
      #nodeName: dgtestlinux01v
      containers:
        - name: authserver
          image: hongyan5682/authserver:latest
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Hong_Kong
---
apiVersion: v1
kind: Service
metadata:
  name: authserver
spec:
  selector:
    app: authserver
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
