apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-setting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-setting-service
  template:
    metadata:
      labels:
        app: base-setting-service
    spec:
      #assigned to master node
      #nodeName: dgtestlinux01v
      containers:
        - name: base-setting-service
          image: hongyan5682/base-setting-service:latest
          imagePullPolicy: Never
          env:
            - name: TZ
              value: Asia/Hong_Kong
---
apiVersion: v1
kind: Service
metadata:
  name: base-setting-service
spec:
  selector:
    app: base-setting-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
