apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      #assigned to master node
      #nodeName: dgtestlinux01v
      containers:
        - name: identity-service
          image: hongyan5682/identity-service:latest
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Hong_Kong
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31002
